event_inherited();
shoot_cooldown = irandom_range(10, 25);
shoot_delay = 45;
enragedRecoil = 8;
enragedFireDuration = 5;
recoil_cooldown = 8;
fire_duration = 5;
fire_timer = fire_duration;
recoil_timer = 0;
enemey_hp = 18;
enemSpeed = 0.15;
base_speed = enemSpeed;
xp = 10;
damage = 5;
bullet_speed = 3;
spawnWeight = 7.5;
enraged = false;
startEnragedLoop = false;
enragedCooldown = (shoot_delay)/2;
enragedDelay = enragedCooldown;
phasePoint1 = enemey_hp*0.85;
ang = 0;

