event_inherited();
shoot_cooldown = irandom_range(10, 25);
shoot_delay = 35;
recoil_cooldown = 2;
fire_duration = 5;
fire_timer = fire_duration;
recoil_timer = 0;
enemey_hp = 18;
enemSpeed = 0.15;
base_enemSpeed = enemSpeed;
xp = 8.5;
damage = 5;
bullet_speed = 3;