event_inherited();
shoot_cooldown = irandom_range(10, 25);
shoot_delay = 45;
enragedRecoil = 8;
enragedFireDuration = 5;
recoil_cooldown = 8;
fire_duration = 5;
fire_timer = fire_duration;
recoil_timer = 0;
 enemyHP = 17;
enemSpeed = 0.15;
baseSpeed = enemSpeed;
damage = 12;
bullet_speed = 3;
enraged = false;
startEnragedLoop = false;
enragedCooldown = (shoot_delay)/2;
enragedDelay = enragedCooldown;
phasePoint1 =  enemyHP*0.7;
ang = 0;

