event_inherited();
shoot_cooldown = irandom_range(10, 25);
shoot_delay = 145;
recoil_cooldown = 12;
fire_duration = 3;
fire_timer = fire_duration;
recoil_timer = 4;
 enemyHP = 17;
baseBulletSpeed = 6;
ang = 0;
enemSpeed = 2.1;
baseSpeed = enemSpeed;
damage = 14;
bullet_speed = 8;
playerPercent = 0;