event_inherited();
 enemyHP = 7.5;
bite_cooldown = 45;
on_cooldown = false;
bite_timer = bite_cooldown;
enemSpeed = 5.45;
baseSpeed = enemSpeed;
contactDamage = 25.5;
damage = contactDamage;
count = 3;