event_inherited();
shoot_cooldown = irandom_range(10, 25);
enemSpeed = 0.6;
bullet_speed = 5.5;
shoot_delay = 200;
recoil_cooldown = 25;
fire_duration = 4;
fire_timer = fire_duration;
recoil_timer = 0;
enemey_hp = 42;
enrage_point = enemey_hp/2;
enraged = false;
xp = 18.5;
damage = 19;
spawnWeight = 12;
ang = irandom_range(35, 60);