event_inherited();
enemey_hp = 1.6;
bite_cooldown = 75;
on_cooldown = false;
bite_timer = bite_cooldown;
enemSpeed = 5.5;
base_speed = enemSpeed;
xp = 3;
damage = 12.5;
spawnWeight = 1.5;
denyHP = true;