event_inherited();
shoot_cooldown = irandom_range(10, 110);
shoot_delay = 160;
enemey_hp = 6.5;
enemSpeed = 2.3;
base_speed = enemSpeed;
xp = 7;
damage = 14.5;
bullet_speed = 6.5;
searchPlayer();
spawnWeight = 4;