event_inherited();
enemyHP = 4.9;
bite_cooldown = 75;
on_cooldown = false;
bite_timer = bite_cooldown;
enemSpeed = 3.45;
baseSpeed = enemSpeed;
xp = 0;
damage = 16.5;
contactDamage = 2;
spawnWeight = 4;
head = noone;
path_cooldown = 10;
follow = noone;
image_xscale = 0.75;
image_yscale = 0.75;
denyHP = true;