event_inherited();
shoot_cooldown = irandom_range(10, 110);
shoot_delay = 160;
enemey_hp = 3.7;
enemSpeed = 4.4;
base_speed = enemSpeed;
damage = 14.5;
bullet_speed = 6.5;
searchPlayer();
image_speed = 0;
rageTimer = 0;
rageBreak = 320;
halfRaged = false;
fullRaged = false;
image_xscale = 2;
image_yscale = 2;