event_inherited();
shoot_cooldown = irandom_range(10, 25);
enemSpeed = 1.05;
baseSpeed = enemSpeed;
bullet_speed = 8;
shoot_delay = 120;
recoil_cooldown =12;
fire_duration = 6;
fire_timer = fire_duration;
recoil_timer = 0;
 enemyHP = 7;
phasePoint1 =  enemyHP/2;
enraged = false;
damage = 9.5;
enragedAngle = 0;
spawnCheck = 0;
spawnNum = 900;