event_inherited();
shoot_cooldown = irandom_range(10, 110);
shoot_delay = 160;
 enemyHP = 4.4;
enemSpeed = 1.2;
baseSpeed = enemSpeed;
damage = 14.5;
bullet_speed = 3.5;
speedBoost = 0;
searchPlayer();