event_inherited();
 enemyHP = 3.6;
shoot_delay = 15;
on_cooldown = false;
bite_timer = shoot_delay;
enemSpeed = 3.25;
baseSpeed = enemSpeed;
damage = 16.5;
contactDamage = damage;
bodyCount = 8;
bodyArray = [];
spawnedBody = false;
image_xscale = 0.75;
image_yscale = 0.75;