event_inherited();
shoot_cooldown = irandom_range(10, 110);
shoot_delay = 160;
enemey_hp = 3.5;
enemSpeed = 0.5;
base_speed = enemSpeed;
xp = 4;
damage = 12.5;
bullet_speed = 5.5;
searchPlayer();
spawnWeight = 1.5;