event_inherited();
denyHP = true;
enemyHP = 1.0;
shoot_delay = 75;
on_cooldown = false;
bite_timer = shoot_delay;
enemSpeed = 4.8;
baseSpeed = enemSpeed;
damage = 15;
contactDamage = damage;
denyHP = false;