event_inherited();
denyHP = true;
enemyHP = 1.0;
shoot_delay = 75;
on_cooldown = false;
bite_timer = shoot_delay;
enemSpeed = 5.2;
baseSpeed = enemSpeed;
damage = 5;
contactDamage = damage;
denyHP = false;