event_inherited();
enemey_hp = 2.8;
bite_cooldown = 45;
on_cooldown = false;
bite_timer = bite_cooldown;
path_cooldown = 5;
enemSpeed = 3.75;
base_speed = enemSpeed;
xp = 2.45;
contactDamage = 10;
damage = contactDamage;
spawnWeight = 0.75;