event_inherited();
enemey_hp = 2.8;
bite_cooldown = 75;
on_cooldown = false;
bite_timer = bite_cooldown;
path_cooldown = 5;
enemSpeed = 3.75;
base_enemSpeed = enemSpeed;
xp = 2.45;
damage = 4;
spawnWeight = 1;