event_inherited();
enemyHP = 3.;
shoot_delay = 45;
on_cooldown = false;
bite_timer = shoot_delay;
path_cooldown = 5;
enemSpeed = 3.75;
baseSpeed = enemSpeed;
contactDamage = 30;
damage = contactDamage;
denyHP = true;